//
//  PathSegmentsIndeces.h
//  OnTheWriteTrack
//
//  Created by Mitch Clutter on 5/29/15.
//  Copyright (c) 2015 Mitch Clutter. All rights reserved.
//

#ifndef OnTheWriteTrack_PathSegmentsIndeces_h
#define OnTheWriteTrack_PathSegmentsIndeces_h

#define cs  [NSNumber numberWithInteger:-1]
#define v0  [NSNumber numberWithInteger:0]
#define v1  [NSNumber numberWithInteger:1]
#define v2  [NSNumber numberWithInteger:2]
#define v3  [NSNumber numberWithInteger:3]
#define v4  [NSNumber numberWithInteger:4]
#define v5  [NSNumber numberWithInteger:5]
#define v6  [NSNumber numberWithInteger:6]
#define v7  [NSNumber numberWithInteger:7]
#define v8  [NSNumber numberWithInteger:8]
#define v9  [NSNumber numberWithInteger:9]
#define v10 [NSNumber numberWithInteger:10]
#define v11 [NSNumber numberWithInteger:11]
#define v12 [NSNumber numberWithInteger:12]
#define v13 [NSNumber numberWithInteger:13]
#define v14 [NSNumber numberWithInteger:14]
#define v15 [NSNumber numberWithInteger:15]
#define v16 [NSNumber numberWithInteger:16]
#define v17 [NSNumber numberWithInteger:17]
#define v18 [NSNumber numberWithInteger:18]
#define v19 [NSNumber numberWithInteger:19]

#define h20 [NSNumber numberWithInteger:20]
#define h21 [NSNumber numberWithInteger:21]
#define h22 [NSNumber numberWithInteger:22]
#define h23 [NSNumber numberWithInteger:23]
#define h24 [NSNumber numberWithInteger:24]
#define h25 [NSNumber numberWithInteger:25]
#define h26 [NSNumber numberWithInteger:26]
#define h27 [NSNumber numberWithInteger:27]
#define h28 [NSNumber numberWithInteger:28]
#define h29 [NSNumber numberWithInteger:29]
#define h30 [NSNumber numberWithInteger:30]
#define h31 [NSNumber numberWithInteger:31]
#define h32 [NSNumber numberWithInteger:32]
#define h33 [NSNumber numberWithInteger:33]
#define h34 [NSNumber numberWithInteger:34]
#define h35 [NSNumber numberWithInteger:35]
#define h36 [NSNumber numberWithInteger:36]
#define h37 [NSNumber numberWithInteger:37]
#define h38 [NSNumber numberWithInteger:38]
#define h39 [NSNumber numberWithInteger:39]

#define a40 [NSNumber numberWithInteger:40]
#define a41 [NSNumber numberWithInteger:41]
#define a42 [NSNumber numberWithInteger:42]
#define a43 [NSNumber numberWithInteger:43]
#define a44 [NSNumber numberWithInteger:44]
#define a45 [NSNumber numberWithInteger:45]
#define a46 [NSNumber numberWithInteger:46]
#define a47 [NSNumber numberWithInteger:47]

#define v48 [NSNumber numberWithInteger:48]
#define v49 [NSNumber numberWithInteger:49]
#define v50 [NSNumber numberWithInteger:50]
#define v51 [NSNumber numberWithInteger:51]
#define v52 [NSNumber numberWithInteger:52]
#define v53 [NSNumber numberWithInteger:53]
#define v54 [NSNumber numberWithInteger:54]
#define v55 [NSNumber numberWithInteger:55]

#define x56 [NSNumber numberWithInteger:56]
#define x57 [NSNumber numberWithInteger:57]
#define x58 [NSNumber numberWithInteger:58]
#define x59 [NSNumber numberWithInteger:59]
#define x60 [NSNumber numberWithInteger:60]
#define x61 [NSNumber numberWithInteger:61]
#define x62 [NSNumber numberWithInteger:62]
#define x63 [NSNumber numberWithInteger:63]

#define c64 [NSNumber numberWithInteger:64]
#define c65 [NSNumber numberWithInteger:65]
#define c66 [NSNumber numberWithInteger:66]
#define c67 [NSNumber numberWithInteger:67]
#define c68 [NSNumber numberWithInteger:68]
#define c69 [NSNumber numberWithInteger:69]
#define c70 [NSNumber numberWithInteger:70]
#define c71 [NSNumber numberWithInteger:71]
#define c72 [NSNumber numberWithInteger:72]
#define c73 [NSNumber numberWithInteger:73]
#define c74 [NSNumber numberWithInteger:74]
#define c75 [NSNumber numberWithInteger:75]

#endif
